name: Default branch workflow
#on:
#  push:
#    branches:
#      - main

on: pull_request
jobs:
  ehoes:
    steps:
      - name: Echo event
        run: echo ${{ github.event }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
